name: StateTools
version: ${project.version}
main: com.danikvitek.statetools.Main
api-version: 1.16
authors: [ Danik_Vitek ]
description: Use different tools to rotate redstone blocks, building blocks or paint paintable blocks

commands:
  statetool:
    aliases:
      - st
      - state_tool
    description: give a state tool

permissions:
  statetools.command.statetool:
    default: op
    description: if can use statetool command